package com.isekai.ssp.helpers;

public enum ContentTone {
    SERIOUS, HUMOROUS, MELANCHOLIC, TRIUMPHANT, MYSTERIOUS, TENSE,
    EXPOSITORY, TECHNICAL, MEDITATIVE, ECSTATIC, IRONIC, ELEGIAC,
    SATIRICAL, INSTRUCTIONAL
}
