package com.isekai.ssp.helpers;

public enum GlossaryType {
    // Existing (narrative)
    CHARACTER_NAME, LOCATION, MAGIC_SPELL, ITEM, CONCEPT, ORGANIZATION, TITLE,
    // Academic/Technical
    SCIENTIFIC_TERM, ABBREVIATION, FORMULA, CITATION_STYLE, METHODOLOGY,
    // Poetic
    ARCHAIC_WORD, POETIC_DEVICE, ALLUSION, LITERARY_REFERENCE,
    // Script
    STAGE_DIRECTION_TERM, INDUSTRY_JARGON,
    // General
    FOREIGN_WORD, PROPER_NOUN, IDIOM, CULTURAL_REFERENCE,
    // Custom
    CUSTOM
}
