package com.isekai.ssp.helpers;

public enum SectionType {
    INTRODUCTION, METHODOLOGY, RESULTS, DISCUSSION, CONCLUSION,
    EXAMPLE, EXERCISE, DEFINITION, PROOF, CASE_STUDY,
    ABSTRACT, BIBLIOGRAPHY, APPENDIX
}
